openapi: 3.0.0
info:
  title: Test Swagger
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ThatWightGuy/test-swagger-git/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /api: {}
components: {}
